### PR TITLE
Don't leave VAR_PREFIX variables in shell (GH #3).

### PR DESCRIPTION
**Pull request by b-long**

### CODE REVIEW

**Comment by b-long** [comment]
@dtenenba Since I can't resolve [SC2013](https://travis-ci.org/Bioconductor/bioc-cm/builds/87116195#L163) ([information](https://github.com/koalaman/shellcheck/wiki/SC20130)), I'm tabling this for today.  I tried a variety of other things, but kept running into issues.  The following evaluates, but keeps the `$VAR_PREFIX...` variables in the shell : 

``` diff
-   for varAndVal in $(grep VAR_PR local_variables | cut -d'=' -f1) ; do
-      # echo "Checking stuff, varAndVal = $varAndVal"
+   grep VAR_PREFIX < local_variables | cut -d'=' -f1 | while IFS= read -r varAndVal; do
       unset "${varAndVal}"
    done
```

@jimhester Any ideas ?

**Comment by b-long** [comment]
@koalaman Any ideas on this?

**Comment by koalaman** [comment]
Use `while ..; do ..; done <  <(grep ...)` instead of a pipe.

The pipe causes a subshell and the variables are only unset in that subshell.

**Comment by b-long** [comment]
You're the best @koalaman :smile: :+1: Thank you so much!

**Comment by b-long** [comment]
@dtenenba FYI, this is fixed and deployed.

**Pull request merged**
